# Generated by Django 4.2.30 on 2026-08-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_student_payment_reminder'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, help_text="Flat KES discount to subtract from the student's total fees", max_digits=10),
        ),
        migrations.AddField(
            model_name='student',
            name='discount_reason',
            field=models.CharField(blank=True, help_text='Why the discount was given', max_length=200),
        ),
    ]
