# Generated by Django 4.2.30 on 2026-08-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_discount_student_discount_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discount_description',
            field=models.TextField(blank=True, help_text='Internal note about this discount (admin only)'),
        ),
    ]
