# Generated by Django 4.2.30 on 2026-08-04 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='price',
        ),
        migrations.AddField(
            model_name='course',
            name='full_course_price',
            field=models.DecimalField(decimal_places=2, default=25000, max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='half_course_price',
            field=models.DecimalField(decimal_places=2, default=15000, max_digits=10),
        ),
        migrations.AddField(
            model_name='course',
            name='test_only_price',
            field=models.DecimalField(decimal_places=2, default=5000, max_digits=10),
        ),
    ]
