# Generated by Django 4.2.30 on 2026-07-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('website', '0001_initial'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(editable=False, max_length=20, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('OTHER', 'Other')], max_length=6)),
                ('national_id', models.CharField(max_length=30, verbose_name='National ID Number')),
                ('address', models.TextField()),
                ('passport_photo', models.ImageField(upload_to='admissions/passports/')),
                ('national_id_image', models.ImageField(upload_to='admissions/ids/', verbose_name='National ID Image')),
                ('preferred_schedule', models.CharField(choices=[('MORNING', 'Morning (8AM-12PM)'), ('AFTERNOON', 'Afternoon (1PM-5PM)'), ('EVENING', 'Evening (5PM-8PM)'), ('WEEKEND', 'Weekend')], default='MORNING', max_length=20)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ENROLLED', 'Enrolled')], default='PENDING', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.branch')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.coursecategory')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='website.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
