# Generated by Django 4.2.30 on 2026-07-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_coursepackage_lessonitem_lesson_type_and_more'),
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.coursepackage'),
        ),
    ]
