# Generated by Django 4.2.30 on 2026-07-30 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='package_choice',
            field=models.CharField(choices=[('FULL', 'Full Course'), ('HALF', 'Half Course'), ('TEST', 'Test Only')], default='FULL', max_length=10),
        ),
    ]
