# Generated by Django 4.2.30 on 2026-08-04 08:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('website', '0002_remove_course_price_course_full_course_price_and_more'),
        ('admissions', '0002_admission_package_choice'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalkInInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('feedback', models.TextField(blank=True, help_text='What they said, interested in, etc.')),
                ('followed_up', models.BooleanField(default=False)),
                ('converted', models.BooleanField(default=False, help_text='Converted to admission/student?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='website.course')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Walk-in Inquiry',
                'verbose_name_plural': 'Walk-in Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
