# Generated by Django 4.2.30 on 2026-09-02 06:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admissions', '0003_walkininquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='The registered user who submitted this admission (from the student app).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_admissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admission',
            name='passport_photo',
            field=models.ImageField(upload_to='admissions/passports/', verbose_name='Passport Size Photo'),
        ),
    ]
