# Generated by Django 4.2.30 on 2026-09-02 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_admission_submitted_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admission',
            name='national_id_image',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/ids/', verbose_name='National ID Image'),
        ),
        migrations.AlterField(
            model_name='admission',
            name='passport_photo',
            field=models.ImageField(blank=True, null=True, upload_to='admissions/passports/', verbose_name='Passport Size Photo'),
        ),
    ]
