from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib import messages
from django.views import View
from django.http import HttpResponse
from .models import DailyLog


class StaffMixin(LoginRequiredMixin, UserPassesTestMixin):
    def test_func(self):
        return self.request.user.role in ('SUPER_ADMIN', 'MANAGER', 'RECEPTIONIST')


class DailyLogListView(StaffMixin, View):
    def get(self, request):
        from datetime import date
        logs = DailyLog.objects.select_related('recorded_by').all()
        filter_date = request.GET.get('date', '')
        if filter_date:
            logs = logs.filter(log_date=filter_date)
        return render(request, 'core/daily_log_list.html', {
            'logs': logs[:50],
            'filter_date': filter_date or str(date.today()),
        })


class DailyLogCreateView(StaffMixin, View):
    def post(self, request):
        title = request.POST.get('title', '').strip()
        description = request.POST.get('description', '').strip()
        log_date = request.POST.get('log_date', '')
        if title:
            DailyLog.objects.create(title=title, description=description, log_date=log_date, recorded_by=request.user)
            messages.success(request, 'Activity logged.')
        return redirect('core:daily_log')


class DailyLogUpdateView(StaffMixin, View):
    def post(self, request, pk):
        log = get_object_or_404(DailyLog, pk=pk)
        log.title = request.POST.get('title', log.title)
        log.description = request.POST.get('description', log.description)
        log.log_date = request.POST.get('log_date', log.log_date)
        log.save()
        messages.success(request, 'Updated.')
        return redirect('core:daily_log')


class DailyLogDeleteView(StaffMixin, View):
    def get(self, request, pk):
        get_object_or_404(DailyLog, pk=pk).delete()
        messages.success(request, 'Deleted.')
        return redirect('core:daily_log')


class DailyLogPDFView(StaffMixin, View):
    def get(self, request):
        from datetime import date
        import io, os
        from reportlab.lib.pagesizes import A4, landscape
        from reportlab.lib import colors
        from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
        from reportlab.lib.units import mm
        from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph, Spacer, HRFlowable, Image

        logs = DailyLog.objects.select_related('recorded_by').all()
        filter_date = request.GET.get('date', '')
        if filter_date:
            logs = logs.filter(log_date=filter_date)

        GREEN = colors.HexColor('#2E7D32')
        GREEN_LIGHT = colors.HexColor('#E8F5E9')

        buf = io.BytesIO()
        doc = SimpleDocTemplate(buf, pagesize=landscape(A4), leftMargin=15*mm, rightMargin=15*mm, topMargin=28*mm, bottomMargin=22*mm)
        styles = getSampleStyleSheet()

        story = []
        # Logo + Title
        logo_path = os.path.join(os.path.dirname(os.path.dirname(os.path.abspath(__file__))), 'static', 'images', 'logo.png')
        logo_data = [[Paragraph("", styles['Normal']), Paragraph("Daily Activity Report", ParagraphStyle('T', parent=styles['Title'], fontSize=18, textColor=colors.HexColor('#1B5E20'), fontName='Helvetica-Bold'))]]
        if os.path.isfile(logo_path):
            logo_data[0][0] = Image(logo_path, width=40, height=40)
        lt = Table(logo_data, colWidths=[50, None])
        lt.setStyle(TableStyle([('VALIGN',(0,0),(-1,-1),'MIDDLE'),('LEFTPADDING',(0,0),(0,0),0)]))
        story.append(lt)
        story.append(Paragraph(f"Date: {filter_date or str(date.today())} | Generated by {request.user.full_name}", ParagraphStyle('S', parent=styles['Normal'], fontSize=9, textColor=colors.HexColor('#666666'))))
        story.append(HRFlowable(width="100%", thickness=1.5, color=GREEN, spaceAfter=8))

        data = [['Time', 'Activity', 'Details', 'Recorded By']]
        for l in logs:
            data.append([l.created_at.strftime('%H:%M'), Paragraph(l.title, styles['Normal']),
                         Paragraph(l.description or '—', ParagraphStyle('small', parent=styles['Normal'], fontSize=7)),
                         l.recorded_by.full_name if l.recorded_by else '—'])

        t = Table(data, colWidths=[40, 180, None, 60], repeatRows=1)
        t.setStyle(TableStyle([
            ('BACKGROUND',(0,0),(-1,0), GREEN), ('TEXTCOLOR',(0,0),(-1,0), colors.white),
            ('FONTNAME',(0,0),(-1,0), 'Helvetica-Bold'), ('FONTSIZE',(0,0),(-1,0), 9),
            ('GRID',(0,0),(-1,-1),0.4,colors.Color(0.85,0.85,0.85)),
            ('FONTSIZE',(0,1),(-1,-1),8), ('VALIGN',(0,0),(-1,-1),'TOP'),
            ('ROWBACKGROUNDS',(0,1),(-1,-1),[colors.white, GREEN_LIGHT]),
            ('TOPPADDING',(0,1),(-1,-1),6), ('BOTTOMPADDING',(0,1),(-1,-1),6),
        ]))
        story.append(t)
        story.append(Spacer(1,5*mm))
        story.append(Paragraph(f"<b>Total: {len(logs)} activities</b> | Greenlight Defensive Driving School",
                               ParagraphStyle('Sum', parent=styles['Normal'], fontSize=9, textColor=colors.HexColor('#1B5E20'))))
        doc.build(story)
        buf.seek(0)
        return HttpResponse(buf, content_type='application/pdf')
