# Generated by Django 4.2.30 on 2026-07-31 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('instructors', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instructor',
            old_name='is_available',
            new_name='is_active',
        ),
        migrations.AddField(
            model_name='instructor',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instructors', to='core.branch'),
        ),
        migrations.AddField(
            model_name='instructor',
            name='license_class',
            field=models.CharField(blank=True, choices=[('A1', 'A1 - Motorcycle'), ('A2', 'A2 - Motorcycle Advanced'), ('B1', 'B1 - Saloon Car'), ('B2', 'B2 - SUV/Jeep'), ('C1', 'C1 - Light Commercial'), ('C2', 'C2 - Heavy Commercial'), ('D1', 'D1 - Light PSV'), ('D2', 'D2 - Heavy PSV'), ('CE', 'CE - Articulated'), ('ALL', 'ALL - All Classes')], max_length=20),
        ),
        migrations.AddField(
            model_name='instructor',
            name='license_expiry',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='instructor',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='instructor',
            name='photo',
            field=models.ImageField(blank=True, upload_to='instructors/'),
        ),
    ]
