# Generated by Django 4.2.30 on 2026-07-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='student_documents/')),
                ('category', models.CharField(choices=[('general', 'General'), ('forms', 'Forms'), ('certificates', 'Certificates'), ('guidelines', 'Guidelines'), ('ntsa', 'NTSA Documents')], default='general', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'title'],
            },
        ),
    ]
