# Generated by Django 4.2.30 on 2026-07-25 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('student_portal', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('ntsa_test', 'NTSA Driving Test'), ('ntsa_exam', 'NTSA Theory Exam'), ('school_event', 'School Event'), ('holiday', 'Holiday / Closure'), ('orientation', 'New Student Orientation'), ('workshop', 'Safety Workshop'), ('other', 'Other')], default='school_event', max_length=20)),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, help_text='Physical location or online link', max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('is_important', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.branch')),
            ],
            options={
                'ordering': ['event_date', 'event_time'],
            },
        ),
    ]
