# Generated by Django 4.2.30 on 2026-08-03 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_student_package_choice'),
        ('student_portal', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdocument',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Leave blank for all students; select one for private document', null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
        migrations.AlterField(
            model_name='studentdocument',
            name='category',
            field=models.CharField(choices=[('general', 'General'), ('theory', 'Theory Materials'), ('forms', 'Forms'), ('certificates', 'Certificates'), ('guidelines', 'Guidelines'), ('ntsa', 'NTSA Documents')], default='general', max_length=20),
        ),
    ]
