# Generated by Django 4.2.30 on 2026-07-24 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NTSARecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pdl_status', models.CharField(choices=[('NOT_APPLIED', 'Not Applied'), ('APPLIED', 'Applied'), ('ISSUED', 'Issued')], default='NOT_APPLIED', max_length=20)),
                ('pdl_date', models.DateField(blank=True, null=True)),
                ('pdl_number', models.CharField(blank=True, max_length=30)),
                ('theory_exam_status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('theory_exam_date', models.DateField(blank=True, null=True)),
                ('theory_exam_score', models.PositiveIntegerField(blank=True, null=True)),
                ('practical_exam_status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('practical_exam_date', models.DateField(blank=True, null=True)),
                ('driving_test_status', models.CharField(choices=[('PENDING', 'Pending'), ('SCHEDULED', 'Scheduled'), ('PASSED', 'Passed'), ('FAILED', 'Failed'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20)),
                ('driving_test_date', models.DateField(blank=True, null=True)),
                ('licence_issued', models.BooleanField(default=False)),
                ('licence_number', models.CharField(blank=True, max_length=30)),
                ('licence_issue_date', models.DateField(blank=True, null=True)),
                ('licence_expiry_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ntsa_record', to='students.student')),
            ],
        ),
    ]
