# Generated by Django 4.2.30 on 2026-07-30 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonitem',
            name='lesson_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical'), ('ASSESSMENT', 'Assessment')], default='PRACTICAL', max_length=20),
        ),
        migrations.AddField(
            model_name='theorylesson',
            name='lesson_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.lessonitem'),
        ),
    ]
