# Generated by Django 4.2.30 on 2026-07-28 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='lessonitem',
            name='lesson_type',
            field=models.CharField(choices=[('THEORY', 'Theory'), ('PRACTICAL', 'Practical'), ('ASSESSMENT', 'Assessment')], default='PRACTICAL', max_length=20),
        ),
        migrations.AddField(
            model_name='theorylesson',
            name='lesson_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='lessons.lessonitem'),
        ),
        migrations.AddField(
            model_name='lessonitem',
            name='packages',
            field=models.ManyToManyField(blank=True, related_name='lesson_items', to='lessons.coursepackage'),
        ),
    ]
